// Copyright (c) 2026 JBBLET. All Rights Reserved.

#pragma once
#include <cstdint>
#include <functional>
#include <string>

#include "finapp/finance/asset/AssetType.hpp"
#include "finapp/finance/common/Currency.hpp"
namespace finance {
enum class TransactionType : uint8_t {
    Buy,
    Sell,
    Deposit,
    Withdrawal,
    Dividend,
    Split,
};

// Canonical name for a transaction type. Throws std::runtime_error on an unknown enumerator.
std::string toString(const TransactionType& transactionType);

// Parses a transaction-type name. Throws std::runtime_error on an unknown name.
TransactionType transactionTypeFromString(const std::string& type);

// Priority used when sorting transactions with equal timestamps.
// Deposits must precede Buys so applyBuy_ sees the cash balance already credited.
// Order: Deposit < Dividend < Buy/Sell < Withdrawal < Split.
int transactionTypePriority(TransactionType t);

struct Transaction {
    std::string id;  // generated by PortfolioService::addTransaction; empty until persisted
    int64_t timestampsMs;
    TransactionType type;
    AssetType assetType;
    std::string assetTicker;
    double quantity;
    double pricePerUnit;
    double fees;
    Currency settlementCurrency;
    bool operator==(const Transaction& other) const { return id == other.id; }
};
}  // namespace finance

namespace std {
// TODO(JBBLET) Change to just a custom hasher to  not pollute the std namespace ??
template <>
struct hash<finance::Transaction> {
    size_t operator()(const finance::Transaction& transaction) const {
        return std::hash<std::string>()(transaction.id);
    }
};
}  // namespace std
